POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Guilherme Torres",
  "email": "guilherme@email.com"
}
###

GET http://localhost:3333/invites/b90d18ac-7deb-4615-a654-14df071cd6a3